config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get "dashboard", to: "dashboard#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :registrations, only: [ :new, :create ]
  resource :session, only: [ :new, :create, :destroy ]
  resources :passwords, param: :token
  resources :jobs
  resources :applicants do
    get "resume", to: "resumes#show"

    member do
      patch :change_stage
    end

    resources :emails, only: [ :index, :new, :create, :show ]
  end
end

app/models/job.rb
class Job < ApplicationRecord
  include PgSearch::Model

  FILTER_PARAMS = %i[ query status sort].freeze

  pg_search_scope :text_search,
    against: %i[ title ],
    using: {
      tsearch: {
        any_word: true,
        prefix: true
      }
    }

  belongs_to :account

  has_many :applicants, dependent: :destroy

  validates :title, presence: true
  validates :location, presence: true
  validates :status, presence: true
  validates :job_type, presence: true
  validates :location_type, presence: true

  has_rich_text :description

  enum :status, {
    draft: "draft",
    open: "open",
    closed: "closed"
  }

  enum :job_type, {
    full_time: "full_time",
    part_time: "part_time",
    contract: "contract",
    internship: "internship"
  }

  enum :location_type, {
    remote: "remote",
    hybrid: "hybrid",
    on_site: "on_site"
  }

  scope :within_account, ->(account_id) { where(account_id: account_id) }
  scope :for_status, ->(status) { status.present? ? where(status: status) : all }
  scope :search, ->(query) { query.present? ? text_search(query) : all }
  scope :sorted, ->(selection) { selection.present? ? apply_sort(selection) : apply_sort(default_sort) }

  def self.apply_sort(selection)
    return if selection.blank?
    sort, direction = selection.split("-")
    order("jobs.#{sort} #{direction}")
  end

  def self.filter(filters)
    sorted(filters["sort"])
      .for_status(filters["status"])
      .search(filters["query"])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  include Filterable

  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :ensure_frame_response, only: %i[ new edit ]
  before_action :authorize_access, only: %i[ show ]

  def index
    @jobs = filter!(Job).within_account(current_account.id)
  end

  def show
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.account = current_account

    respond_to do |format|
      if @job.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("jobs_container", partial: "jobs/job", locals: { job: @job })
        end
        format.html { redirect_to @job, notice: "Job was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("job_#{@job.id}_row", partial: "jobs/job", locals: { job: @job }),
            turbo_stream.replace("job_#{@job.id}_detail", partial: "jobs/details", locals: { job: @job })
          ]
        end
        format.html { redirect_to @job, notice: "Job was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy!

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("job_#{@job.id}_row")
      end
      format.html { redirect_to jobs_path, status: :see_other, notice: "Job was successfully destroyed." }
    end
  end

  private
    def set_job
      @job = Job.find(params.expect(:id))
    end

    def job_params
      params.expect(job: [ :title, :description, :location, :status, :job_type, :location_type, :salary_budget ])
    end

    def authorize_access
      redirect_to jobs_path, alert: "Unauthorized access." if @job.account != current_account
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def job_status_color(status)
    {
      draft: "bg-amber-50 text-amber-500 ring-amber-400/20",
      open: "bg-green-50 text-green-700 ring-green-600/20",
      closed: "bg-rose-50 text-rose-700 ring-rose-600/20"
    }[status.to_sym]
  end

  def jobs_sort_options
    [
      [ "Newest", "created_at-desc" ],
      [ "Oldest", "created_at-asc" ],
      [ "Title", "title-asc" ]
    ]
  end

  def jobs_status_filter_options
    Job.statuses.values.map { |value| [ value.humanize, value ] }
  end
end

app/views/jobs/_details.html.erb
<div id="<%= dom_id job %>_detail">
  <div class="mt-2 md:flex md:items-center md:justify-between">
    <div class="min-w-0 flex-1">
      <h2
        class="
          text-2xl font-bold leading-7 text-white sm:truncate sm:text-3xl
          sm:tracking-tight
        "
      ><%= job.title %></h2>
      <div class="mt-1 flex flex-col sm:mt-0 sm:flex-row sm:flex-wrap sm:space-x-6">
        <div class="mt-2 flex items-center text-sm text-gray-300">
          <%= inline_svg_tag "briefcase.svg",
          class: "mr-1.5 h-5 w-5 flex-shrink-0 text-gray-500" %>
          <%= job.job_type.dasherize.humanize %>
        </div>
        <div class="mt-2 flex items-center text-sm text-gray-300">
          <%= inline_svg_tag "map-pin.svg",
          class: "mr-1.5 h-5 w-5 flex-shrink-0 text-gray-500" %>
          <%= job.location %>
          (<%= job.location_type.dasherize.humanize %>)
        </div>
        <% if job.salary_budget.present? %>
          <div class="mt-2 flex items-center text-sm text-gray-300">
            <%= inline_svg_tag "banknotes.svg",
            class: "mr-1.5 h-5 w-5 flex-shrink-0 text-gray-500" %>
            <%= job.salary_budget %>
          </div>
        <% end %>
        <div class="mt-2 flex items-center text-sm text-gray-300">
          <span
            class="
              inline-flex items-center rounded-md px-2 py-1 text-xs font-medium ring-1
              ring-inset <%= job_status_color(job.status) %>
            "
          >
            <%= job.status.humanize %>
          </span>
        </div>
      </div>
    </div>
    <div class="mt-5 flex lg:ml-4 lg:mt-0">
      <span class="">
        <%= link_to job_path(job, format: "html"), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this job?" }, class: "inline-flex items-center rounded-md bg-rose-500 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-rose-400" do %>
          <%= inline_svg_tag "trash.svg", class: "-ml-0.5 mr-1.5 h-5 w-5" %>
          Delete
        <% end %>
      </span>
      <span class="ml-3 ">
        <%= button_to edit_job_path(job), method: :get, data: { turbo_frame: "modal" }, class: "inline-flex items-center rounded-md bg-white/10 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-white/20" do %>
          <%= inline_svg_tag "pencil-square.svg", class: "-ml-0.5 mr-1.5 h-5 w-5" %>
          Edit
        <% end %>
      </span>
    </div>
  </div>
  <div class="mt-8 md:flex md:items-center md:justify-between">
    <div class="text-white" %>
      <%= raw job.description %>
    </div>
  </div>
</div>

app/views/jobs/_filter_form.html.erb
<%= form_with(
  url: jobs_path,
  method: :get,
  class: "flex items-baseline",
  data: {
    controller: "form",
    form_target: "form",
    turbo_frame: "jobs",
    }
  ) do |form| %>
  <div>
    <%= form.label :sort, class: "sr-only" %>
    <%= form.select :sort,
                options_for_select(
                  jobs_sort_options,
                  fetch_filter_key(Job, current_user.id, "sort"),
                ),
                { disabled: "", prompt: "Sort by" },
                {
                  data: {
                    action: "change->form#submit",
                  },
                  class:
                    "block w-28 rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 text-sm sm:leading-6 [&_*]:text-black",
                } %>
  </div>
  <div class="ml-2">
    <%= form.label :status, class: "sr-only" %>
    <%= form.select :status,
                options_for_select(
                  jobs_status_filter_options,
                  fetch_filter_key(Job, current_user.id, "status"),
                ),
                { include_blank: "All Statuses" },
                {
                  data: {
                    action: "change->form#submit",
                  },
                  class:
                    "block w-28 rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 text-sm sm:leading-6 [&_*]:text-black",
                } %>
  </div>
  <div class="ml-2">
    <%= form.label :query, class: "sr-only" %>
    <%= form.text_field :query,
                    placeholder: "Search",
                    value: fetch_filter_key(Job, current_user.id, "query"),
                    data: {
                      action: "input->form#submit",
                    },
                    class:
                      "block w-full sm:w-44 rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 text-sm sm:leading-6 [&_*]:text-black" %>
  </div>
<% end %>

app/views/jobs/_form.html.erb
<%= form_with model: job, id: "job_form", class: "p-4 md:p-5" do |form| %>
  <div class="space-y-12">
    <div class="border-b border-white/10 pb-12">
      <% if job.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(job.errors.count, "error") %>
            prohibited this job from being saved:</h2>

          <ul>
            <% job.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
        <div class="col-span-full">
          <%= form.label :title, class: "block text-sm font-medium leading-6 text-white" %>
          <div class="mt-2">
            <%= form.text_field :title,
                            class:
                              "block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6" %>
          </div>
        </div>

        <div class="col-span-full">
          <%= form.label :description, class: "block text-sm font-medium leading-6 text-white" %>
          <div class="mt-2">
            <%= form.rich_text_area :description,
                                class:
                                  "block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6" %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <%= form.label :location, class: "block text-sm font-medium leading-6 text-white" %>
          <div class="mt-2">
            <%= form.text_field :location,
                            class:
                              "block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6" %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <%= form.label :location_type,
                     class: "block text-sm font-medium leading-6 text-white " %>
          <div class="mt-2">
            <%= form.select :location_type,
                        options_for_select(
                          Job.location_types.map do |key, _value|
                            [key.dasherize.humanize, key]
                          end,
                          form.object.location_type,
                        ),
                        {},
                        {
                          class:
                            "block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6 [&_*]:text-black",
                        } %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <%= form.label :status, class: "block text-sm font-medium leading-6 text-white " %>
          <div class="mt-2">
            <%= form.select :status,
                        options_for_select(
                          Job.statuses.map { |key, _value| [key.humanize, key] },
                          form.object.status,
                        ),
                        {},
                        {
                          class:
                            "block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6 [&_*]:text-black",
                        } %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <%= form.label :job_type, class: "block text-sm font-medium leading-6 text-white " %>
          <div class="mt-2">
            <%= form.select :job_type,
                        options_for_select(
                          Job.job_types.map { |key, _value| [key.dasherize.humanize, key] },
                          form.object.job_type,
                        ),
                        {},
                        {
                          class:
                            "block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6 [&_*]:text-black",
                        } %>
          </div>
        </div>

        <div class="col-span-full">
          <%= form.label :salary_budget,
                     class: "block text-sm font-medium leading-6 text-white" %>
          <div class="mt-2">
            <%= form.text_field :salary_budget,
                            class:
                              "block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6" %>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">

    <%= link_to "Cancel",
    "#",
    data: {
      action: "modal#close",
    },
    class: "text-sm font-semibold leading-6 text-white" %>
    <%= form.button class: "
            rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white shadow-sm
            hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2
            focus-visible:outline-offset-2 focus-visible:outline-indigo-500" do %>
      <span class="show-when-enabled">Save</span>
      <span class="show-when-disabled">Saving...</span>
    <% end %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<tr id="<%= dom_id job %>_row">
  <td class="py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0 ">
    <%= link_to job.title, job_path(job), data: { turbo: false } %>
    <dl class="font-normal lg:hidden">
      <dt class="sr-only">Location</dt>
      <dd class="mt-1 truncate text-gray-300"><%= job.location %></dd>
      <dt class="sr-only">Location Type</dt>
      <dd class="mt-1 truncate text-gray-300"><%= job.location_type.dasherize.humanize %></dd>
      <dt class="sr-only">Job Type</dt>
      <dd class="mt-1 truncate text-gray-300"><%= job.job_type.dasherize.humanize %></dd>
      <dt class="sr-only">Salary Budget</dt>
      <dd class="mt-1 truncate text-gray-300"><%= job.salary_budget %></dd>
    </dl>
  </td>
  <td class="hidden px-3 py-4 text-sm text-gray-300 lg:table-cell "><%= job.location %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-300 lg:table-cell "><%= job.location_type.dasherize.humanize %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-300 lg:table-cell "><%= job.job_type.dasherize.humanize %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-300 lg:table-cell "><%= job.salary_budget %></td>
  <td class="px-3 py-4 text-sm text-gray-300">
    <span
      class="
        inline-flex items-center rounded-md px-2 py-1 text-xs font-medium ring-1
        ring-inset <%= job_status_color(job.status) %>
      "
    >
      <%= job.status.humanize %>
    </span>
  </td>
  <td class="relative py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0 ">
    <%= link_to job_path(job), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this job?" }, class: "text-rose-400 hover:text-rose-300" do %>
      <span class="sr-only">Delete</span>
      <%= inline_svg_tag "trash.svg", class: "h-5 w-5 inline-block" %>
    <% end %>
    <%= link_to edit_job_path(job), data: { turbo_frame: "modal" }, class: "text-indigo-400 hover:text-indigo-300 ml-1" do %>
      <span class="sr-only">Edit</span>
      <%= inline_svg_tag "pencil-square.svg", class: "h-5 w-5 inline-block" %>
    <% end %>

  </td>
</tr>

app/views/jobs/_table.html.erb
<%= turbo_frame_tag "jobs" do %>
  <table class="min-w-full divide-y divide-gray-700">
    <thead>
      <tr>
        <th
          scope="col"
          class="
            py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-white sm:pl-0
          "
        >Title</th>
        <th
          scope="col"
          class="
            hidden px-3 py-3.5 text-left text-sm font-semibold text-white lg:table-cell
          "
        >Location</th>
        <th
          scope="col"
          class="
            hidden px-3 py-3.5 text-left text-sm font-semibold text-white lg:table-cell
          "
        >Location Type</th>
        <th
          scope="col"
          class="
            hidden px-3 py-3.5 text-left text-sm font-semibold text-white lg:table-cell
          "
        >Job Type</th>
        <th
          scope="col"
          class="
            hidden px-3 py-3.5 text-left text-sm font-semibold text-white lg:table-cell
          "
        >Salary Budget</th>
        <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-white">Status</th>
        <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
          <span class="sr-only">Action Links</span>
        </th>
      </tr>
    </thead>
    <tbody id="jobs_container" class="divide-y divide-gray-800">
      <%= render jobs %>
    </tbody>
  </table>
<% end %>

app/views/jobs/edit.html.erb
<%= render ModalComponent.new(title: "Edit Job") do %>
  <%= render "form", job: @job %>
<% end %>

app/views/jobs/index.html.erb
<div class="md:flex md:items-center md:justify-between">
  <div class="min-w-0 flex-1">
    <h2
      class="
        text-2xl font-bold leading-7 text-white sm:truncate sm:text-3xl
        sm:tracking-tight
      "
    >Jobs</h2>
  </div>
  <div class="mt-4 flex md:ml-4 md:mt-0">
    <%= link_to "Create a job",
    new_job_path,
    data: {
      turbo_frame: "modal",
    },
    class:
      "inline-flex items-center rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500" %>
  </div>
</div>

<div class="mt-8 flex justify-end">
  <%= render "jobs/filter_form" %>
</div>

<div class="mt-4 flow-root">
  <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <%= render "jobs/table", jobs: @jobs %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<%= render ModalComponent.new(title: "Create New Job") do %>
  <%= render "form", job: @job %>
<% end %>

app/views/jobs/show.html.erb
<%= render "shared/breadcrumbs",
breadcrumbs: [
  { title: "Jobs", path: jobs_path },
  { title: @job.title, path: job_path(@job) },
] %>
<%= render "jobs/details", job: @job %>